name: Auto-generate gallery

on:
  push:
    paths:
      - 'metadata.csv'
      - 'generate_gallery.py'
      - '.github/workflows/autogenerate.yml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate gallery HTML
        run: python generate_gallery.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add index.html
          git commit -m "Auto-update gallery" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}

